config/routes.rb
Rails.application.routes.draw do
  resources :rooms

  devise_for :users
  resources :reservations

  resources :posts

  root to: 'welcome#index'
  get '/about_us', to: 'welcome#about'
  get '/contact', to: 'welcome#contact'
  get '/privacy_policy', to: 'welcome#privacy_policy'
  get '/terms_and_conditions', to: 'welcome#terms_and_conditions'


  get "*path", to: redirect('/')
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
  has_many :replies, class_name: 'Post'

  def self.roots
    where(parent_id: nil)
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new]
  before_action :ensure_current_user_creator!, only: [:edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.roots
    @reservation = Reservation.new
    respond_to do |format|
      format.html { render :index }
      format.json do 
        if params[:room_id]
          @reservations = @reservations.select{ |reserve| reserve.room_id == params[:room_id].to_i }
        end
      end
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
    @reservation.parent_id = params[:parent_id]
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    start_time = reservation_params["time_in(4i)"] + ":" + reservation_params["time_in(5i)"]
    end_time = reservation_params["time_out(4i)"] + ":" + reservation_params["time_out(5i)"]
    @reservation.time_in = start_time
    @reservation.time_out = end_time
    @reservation.user_id = current_user.id
    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
      start_time = reservation_params["time_in(4i)"] + ":" + reservation_params["time_in(5i)"]
      end_time = reservation_params["time_out(4i)"] + ":" + reservation_params["time_out(5i)"]
      @reservation.time_in = start_time
      @reservation.time_out = end_time
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:parent_id, :title, :description, :room_id, :type_of_reservation, :date, :time_in, :time_out, :open_to_public)
    end

    def ensure_current_user_creator!
      unless current_user.id == @reservation.user_id
        sign_out current_user
        redirect_to root_path
      return false
    end
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<div class="form-left">
  
<% if @reservation %>
  <%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :type_of_reservation %><br>
    <%= f.select(:type_of_reservation, options_for_select(["Rehearsal", "Concert", "Lecture", "Recording Session"])) %>
  </div>
  <div class="field">
    <%= f.label :room_id %><br>
    <%= f.select :room_id,
      Room.all.collect { |r| [r.name, r.id]},
      :selected => @room_id %>
  </div>
</div>
<div class="form-right">
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </div>
  <div class="field">
    <%= f.label :time_in %><br>
    <%= f.time_select(:time_in, {minute_step: 15, ampm: true, start_hour: 7, end_hour: 23, selected: 10}) %>
  </div>
  <div class="field">
    <%= f.label :time_out %><br>
    <%= f.time_select(:time_out, {minute_step: 15, ampm: true, start_hour: 7, end_hour: 23, selected: 11}) %>
  </div>
  <div class="field">
    <%= f.label :open_to_public %><br>
    <%= f.check_box :open_to_public %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
<% end %>
</div>

app/views/reservations/_reservation.html.erb
<h1><b><%= reservation.title %></b></h1>
<% if current_user && (reservation.user_id == current_user.id ) %>
	<%= link_to "Edit", edit_reservation_path(reservation) %>
	<%= link_to "Delete", reservation, method: :delete, confirm: 'Are you sure?' %>
<% end %>
<div class="description" style="background-color: #EEEEEE;">
  <p><%= reservation.description %></p>
</div>
<p>Posted by: <%= reservation.user.name %>
, Type: <%= reservation.type_of_reservation %>
, Date: <%= reservation.date %>
, Room: <%= reservation.room.name %>
, Start Time: <%= reservation.time_in %>
, End Time: <%= reservation.time_out %>
, Open to the Public? <%= reservation.open_to_public %>
, Made by: <%= reservation.user.name %></p>

<%= link_to "Reply", new_post_path(reservation_id: reservation.id) %>
<ul class="discussion-title">
  <% reservation.replies.each do |reply| %>
    <li>
      <%= render reply %>
    </li>
  <% end %>
</ul>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reservations</h1>

<% if user_signed_in? %>
  <div class="modal">
    <label for="modal-1">
      <div class="modal-trigger">Make a Reservation</div>
    </label>
    <input class="modal-state" id="modal-1" type="checkbox" />
    <div class="modal-fade-screen">
      <div class="modal-inner">
        <label class="modal-close" for="modal-1"></label>
        <h1>Make a reservation</h1>
        <p class="modal-content"><div class="something"><%= render 'form' %></div></p>
      </div>
    </div>
  </div>
<% end %>

<div class="button-group">
  <label>
    <input type="radio" name="button-group" class="button-1" checked>
    <span class="button-group-item">Show all</span>
  </label>
  <label>
    <input type="radio" name="button-group" class="button-2" value="2">
    <span class="button-group-item">Mountain King Hall</span>
  </label>
  <label>
    <input type="radio" name="button-group" class="button-3" value="3">
    <span class="button-group-item">Al Pacino Recording Studio</span>
  </label>
  <label>
    <input type="radio" name="button-group" class="button-4" value="4">
    <span class="button-group-item">Clear Heights Room</span>
  </label>
  <label>
    <input type="radio" name="button-group" class="button-5" value="5">
    <span class="button-group-item">Hall of Destiny</span>
  </label>
</div>



<div id='calendar'></div>

<ul>
  <% @reservations.each do |reservation| %>
    <li><%= render reservation %></li>
  <% end %>
</ul>


<br>


<!-- :type_of_reservation, :date, :time_in, :time_out, :open_to_public -->

app/views/reservations/new.html.erb
<%= render 'form' %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @reservation.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @reservation.description %>
</p>

<p>
  <strong>Type of reservation:</strong>
  <%= @reservation.type_of_reservation %>
</p>

<p>
  <strong>Room:</strong>
  <%= @reservation.room.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @reservation.date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @reservation.time_in %>
</p>

<p>
  <strong>End time:</strong>
  <%= @reservation.time_out %>
</p>

<p>
  <strong>Open to public:</strong>
  <%= @reservation.open_to_public %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>