config/routes.rb
Rails.application.routes.draw do
  resources :rooms

  devise_for :users
  resources :reservations

  resources :posts

  root to: 'welcome#index'
  get '/about_us', to: 'welcome#about'
  get '/contact', to: 'welcome#contact'
  get '/privacy_policy', to: 'welcome#privacy_policy'
  get '/terms_and_conditions', to: 'welcome#terms_and_conditions'


  get "*path", to: redirect('/')
end

app/models/room.rb
class Room < ActiveRecord::Base
	has_many :reservations, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_filter :ensure_admin!, except: [:index, :show]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description)
    end

    def ensure_admin!
      unless current_user && current_user.admin?
        sign_out current_user
        redirect_to root_path
      return false
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All of our Amazing Rooms</h1>

<ul class="accordion-tabs">
  <li class="tab-header-and-content">
    <a href="javascript:void(0)" class="is-active tab-link"><%= @rooms[0].name %></a>
    <div class="tab-content">
      <%= image_tag("Carnegie-Hall-New-York-City.jpg", :alt => "cavatina rooms") %>
      <p><%= @rooms[0].description %> </br>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt pellentesque lorem, id suscipit dolor rutrum id. Morbi facilisis porta volutpat. Fusce adipiscing, mauris quis congue tincidunt, sapien purus suscipit odio, quis dictum odio tortor in sem. Ut sit amet libero nec orci mattis fringilla. Praesent eu ipsum in sapien tincidunt molestie sed ut magna. Nam accumsan dui at orci rhoncus pharetra tincidunt elit ullamcorper. Sed ac mauris ipsum. Nullam imperdiet sapien id purus pretium id aliquam mi ullamcorper.
        <% if current_user && current_user.admin? %>
          <%= link_to 'Edit', edit_room_path(@rooms[0]) %> |
          <%= link_to 'Destroy', @rooms[0], method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </p>
    </div>
  </li>
  <li class="tab-header-and-content">
    <a href="javascript:void(0)" class="tab-link"><%= @rooms[1].name %></a>
    <div class="tab-content">
      <%= image_tag("Symphony_Hall_Birmingham.jpg", :alt => "cavatina rooms") %>
      <p><%= @rooms[1].description %></br>
      Ut laoreet augue et neque pretium non sagittis nibh pulvinar. Etiam ornare tincidunt orci quis ultrices. Pellentesque ac sapien ac purus gravida ullamcorper. Duis rhoncus sodales lacus, vitae adipiscing tellus pharetra sed. Praesent bibendum lacus quis metus condimentum ac accumsan orci vulputate. Aenean fringilla massa vitae metus facilisis congue. Morbi placerat eros ac sapien semper pulvinar. Vestibulum facilisis, ligula a molestie venenatis, metus justo ullamcorper ipsum, congue aliquet dolor tortor eu neque. Sed imperdiet, nibh ut vestibulum tempor, nibh dui volutpat lacus, vel gravida magna justo sit amet quam. Quisque tincidunt ligula at nisl imperdiet sagittis. Morbi rutrum tempor arcu, non ultrices sem semper a. Aliquam quis sem mi.
        <% if current_user && current_user.admin? %>
          <%= link_to 'Edit', edit_room_path(@rooms[1]) %> |
          <%= link_to 'Destroy', @rooms[1], method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </p>
    </div>
  </li>
  <li class="tab-header-and-content">
    <a href="javascript:void(0)" class="tab-link"><%= @rooms[2].name %></a>
    <div class="tab-content">
      <%= image_tag("goldenhall.jpg", :alt => "cavatina rooms") %>
      <p><%= @rooms[2].description %></br>
      onec mattis mauris gravida metus laoreet non rutrum sem viverra. Aenean nibh libero, viverra vel vestibulum in, porttitor ut sapien. Phasellus tempor lorem id justo ornare tincidunt. Nulla faucibus, purus eu placerat fermentum, velit mi iaculis nunc, bibendum tincidunt ipsum justo eu mauris. Nulla facilisi. Vestibulum vel lectus ac purus tempus suscipit nec sit amet eros. Nullam fringilla, enim eu lobortis dapibus, quam magna tincidunt nibh, sit amet imperdiet dolor justo congue turpis.
        <% if current_user && current_user.admin? %>
          <%= link_to 'Edit', edit_room_path(@rooms[2]) %> |
          <%= link_to 'Destroy', @rooms[2], method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </p>    
    </div>
  </li>
  <li class="tab-header-and-content">
    <a href="javascript:void(0)" class="tab-link"><%= @rooms[3].name %></a>
    <div class="tab-content">
      <%= image_tag("leipzig.jpg", :alt => "cavatina rooms") %>
      <p><%= @rooms[3].description %></br>
      Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus dui urna.
        <% if current_user && current_user.admin? %>
          <%= link_to 'Edit', edit_room_path(@rooms[3]) %> |
          <%= link_to 'Destroy', @rooms[3], method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </p>
    </div>
  </li>
</ul>

<br>

<% if current_user && current_user.admin? %>
  <%= link_to 'New Room', new_room_path %> |
<% end %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %> |